### ISSUE TITLE
Error when hooked function returns tuple

### ISSUE THREAD

**Issue by joelburget** [HP2706/Auto_HookPoint#2]
(Related to #1)

Example here: https://gist.github.com/joelburget/967a38065e1c519f782c95e108a26f92

You can see that `Auto_HookPoint` installs a hook on `rotary_emb`, which runs on this line: `cos, sin = self.rotary_emb(value_states, seq_len=kv_seq_len)`. TransformerLens calls `resid_stream = tensor.detach().to(device)` and this fails with `'tuple' object has no attribute 'detach'`.

Not sure the right solution here. You could not call the hook if you detect that `original_forward` returns a non-tensor?

**Comment by HP2706** [comment]
i tried to reproduce the issue and i think the problem is that hookedRootModule when running with cache assumes it is receiving a tensor(which i think is generally not a great assumption to make) when it is receiving a tuple of tensors as self.rotary_embeddings is hooked and this returns a tuple. 

if you look at transformer_lens.hook_points.py
```python
 def save_hook(tensor: torch.Tensor, hook: HookPoint, is_backward: bool):
          assert hook.name is not None
          hook_name = hook.name
          if is_backward:
              hook_name += "_grad"
          if remove_batch_dim:
              cache[hook_name] = tensor.detach().to(device)[0]
          else:
              cache[hook_name] = tensor.detach().to(device)
```

and since in your code you are not calling super().run_with_cache with names_filter all activations will be cached also from hook_points that receive non-tensors.

when running with names_filter this error is circumvented. A solution would look like this
```python
def run_with_cache(self, *model_args, return_cache_object=True, remove_batch_dim=False, **kwargs):
        names_filter = kwargs.get("names_filter", None)
        out, cache_dict = super().run_with_cache(
            *model_args, remove_batch_dim=remove_batch_dim, names_filter=names_filter
        )
        if return_cache_object:
            cache = ActivationCache(cache_dict, self, has_batch_dim=not remove_batch_dim)
            return out, cache
        else:
            return out, cache_dict
```
However i receive other errors as i have not tested the library for compatability with sae_lens and sae_lens.

in terms of getting this to work i will try, however it might be that sae_lens is so opinionated about how the input model is implemented that this would not be possible without a more extensive integration with  transformer_lens.

**Comment by joelburget** [comment]
Thanks for taking a look! (I agree with your analysis).

When running your modified code I see:

```
File [~/code/github/TransformerLens/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1695](http://localhost:8888/lab/tree/~/code/github/TransformerLens/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1694), in Module.__getattr__(self, name)
   1693     if name in modules:
   1694         return modules[name]
-> 1695 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'HookedModule' object has no attribute 'w1'
```

I haven't tested this but I'd bet you just need to add `__contains__` to `HookedClass` (which already has `__getattr__`).

**Comment by HP2706** [comment]
yeah i got it to work you can check sae_lens in the examples folder. 

Unfortunately this is with a few caveats, as run_with_cache as i have already mentioned only works for tensor outputs. Sae_lens is also quite strict in terms of the tensors having to be in shape [batch, seq_len, d_hidden] so for instance the SparseMLP gate output which i think is the most interesting part to interpret,  is shape [batch_size*seq_len, n_experts] and this gives an error.

I think the idea of having a HookedTransformerAdapter is quite nice and is something i will consider adding to the library.
